### ISSUE TITLE
open redirect_uri in browser [5]. Also you can use 2fa_supported param

### ISSUE THREAD

**Issue by Profesor08** [vodka2/vk-audio-token#15]
Вот такая штука. Не разрешает авторизоваться. Присылает url, но переходить по нему бесполезно. Может как-то по другому надо настраивать аккаунт? Или как-то обыграть эту штуку?

`docker run -t vk-audio-tokens:latest php src/cli/vk-audio-token.php -m <login> <pass>`

```
Getting new android checkin auth data...

Receiving token...

Fatal error: Uncaught Vodka2\VKAudioToken\TokenException: Can't obtain token. Error extra: (object) array(
   'error' => 'need_validation',
   'validation_type' => '2fa_app',
   'validation_sid' => '2fa_10601533_2685278_698885553331113785',
   'phone_mask' => '+456 *** * ** 78',
   'error_description' => 'open redirect_uri in browser [5]. Also you can use 2fa_supported param',
   'redirect_uri' => 'https://m.vk.com/login?act=authcheck&api_hash=49f6111d8333222406',
) in /src/Vodka2/VKAudioToken/TokenReceiver.php:42
Stack trace:
#0 /src/Vodka2/VKAudioToken/TokenReceiver.php(24): Vodka2\VKAudioToken\TokenReceiver->getNonRefreshed()
#1 /src/cli/vk-audio-token.php(142): Vodka2\VKAudioToken\TokenReceiver->getToken()
#2 {main}
  thrown in /src/Vodka2/VKAudioToken/TokenReceiver.php on line 42
```

**Comment by vodka2** [comment]
Добавил поддержку двухфакторной авторизации., лучше поздно, чем никогда. Хотя и до этого можно было использовать отдельный пароль для приложения.
